"""14th  revise

Revision ID: 069820748a65
Revises: 2fa7e582c228
Create Date: 2025-10-10 11:50:51.366955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '069820748a65'
down_revision: Union[str, None] = '2fa7e582c228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shopping_carts', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_carts', type_='unique')
    # ### end Alembic commands ###
