"""revise Art table fields

Revision ID: 1e51d9d1283f
Revises: 7eec7ce07cc2
Create Date: 2026-04-19 17:42:00.918541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e51d9d1283f'
down_revision: Union[str, None] = '7eec7ce07cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arts', sa.Column('genres', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('arts', sa.Column('medium', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('arts', 'Medium')
    op.drop_column('arts', 'Genres')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arts', sa.Column('Genres', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('arts', sa.Column('Medium', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('arts', 'medium')
    op.drop_column('arts', 'genres')
    # ### end Alembic commands ###
