"""revise model relations

Revision ID: 2d281108a4b2
Revises: d0ee2e676252
Create Date: 2026-01-14 16:15:06.928202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d281108a4b2'
down_revision: Union[str, None] = 'd0ee2e676252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arts', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arts', 'status')
    # ### end Alembic commands ###
