"""13th  revise

Revision ID: 2fa7e582c228
Revises: 7e7d95b7256b
Create Date: 2025-10-09 16:55:54.960839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2fa7e582c228'
down_revision: Union[str, None] = '7e7d95b7256b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shopping_carts_work_id_fkey', 'shopping_carts', type_='foreignkey')
    op.drop_column('shopping_carts', 'work_id')
    op.add_column('works', sa.Column('shopping_cart_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'works', 'shopping_carts', ['shopping_cart_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.drop_column('works', 'shopping_cart_id')
    op.add_column('shopping_carts', sa.Column('work_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('shopping_carts_work_id_fkey', 'shopping_carts', 'works', ['work_id'], ['uid'])
    # ### end Alembic commands ###
