"""delete artist table, combine artist with user

Revision ID: 47a0e3edf42c
Revises: 4d5deca323cb
Create Date: 2026-01-30 11:53:48.796644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47a0e3edf42c'
down_revision: Union[str, None] = '4d5deca323cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists')
    op.drop_constraint('arts_artist_id_fkey', 'arts', type_='foreignkey')
    op.create_foreign_key(None, 'arts', 'users', ['artist_id'], ['uid'])
    op.add_column('users', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'bio')
    op.drop_constraint(None, 'arts', type_='foreignkey')
    op.create_foreign_key('arts_artist_id_fkey', 'arts', 'artists', ['artist_id'], ['uid'])
    op.create_table('artists',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='artists_pkey')
    )
    # ### end Alembic commands ###
