"""change work to art

Revision ID: 513722e56add
Revises: b897fca2110a
Create Date: 2025-12-08 12:55:59.165666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '513722e56add'
down_revision: Union[str, None] = 'b897fca2110a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arts',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('shopping_cart_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.uid'], ),
    sa.ForeignKeyConstraint(['shopping_cart_id'], ['shopping_carts.uid'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('works')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('shopping_cart_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.uid'], name='works_artist_id_fkey'),
    sa.ForeignKeyConstraint(['shopping_cart_id'], ['shopping_carts.uid'], name='works_shopping_cart_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.uid'], name='works_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('uid', name='works_pkey')
    )
    op.drop_table('arts')
    # ### end Alembic commands ###
