"""add shopping cart to user

Revision ID: 60f241c30029
Revises: da1feba7514b
Create Date: 2026-04-03 17:56:33.621225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60f241c30029'
down_revision: Union[str, None] = 'da1feba7514b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shopping_cart_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'shopping_carts', ['shopping_cart_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'shopping_cart_id')
    # ### end Alembic commands ###
