"""adjust shopping cart model

Revision ID: 67273c1f2fc6
Revises: 1e51d9d1283f
Create Date: 2026-04-27 11:33:46.918679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67273c1f2fc6'
down_revision: Union[str, None] = '1e51d9d1283f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_carts', sa.Column('uid', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_carts', 'uid')
    # ### end Alembic commands ###
