"""seventh  revise

Revision ID: 6a29c310e5d8
Revises: a0034f7a3f06
Create Date: 2025-10-08 18:19:17.009018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a29c310e5d8'
down_revision: Union[str, None] = 'a0034f7a3f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_carts',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('added_date', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('works', sa.Column('shopping_cart_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'works', 'shopping_carts', ['shopping_cart_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.drop_column('works', 'shopping_cart_id')
    op.drop_table('shopping_carts')
    # ### end Alembic commands ###
