"""revise shopping cart

Revision ID: 7470a48e65d9
Revises: a6f5f0fc37ee
Create Date: 2026-01-11 15:15:35.144296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7470a48e65d9'
down_revision: Union[str, None] = 'a6f5f0fc37ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('arts_shopping_cart_id_fkey', 'arts', type_='foreignkey')
    op.drop_column('arts', 'shopping_cart_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arts', sa.Column('shopping_cart_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('arts_shopping_cart_id_fkey', 'arts', 'shopping_carts', ['shopping_cart_id'], ['uid'])
    # ### end Alembic commands ###
