"""12th  revise

Revision ID: 7e7d95b7256b
Revises: 3e51aa8f54e9
Create Date: 2025-10-09 16:39:12.595403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e7d95b7256b'
down_revision: Union[str, None] = '3e51aa8f54e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('shopping_cart_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'works', 'shopping_carts', ['shopping_cart_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.drop_column('works', 'shopping_cart_id')
    # ### end Alembic commands ###
