"""revise db model

Revision ID: 927c31e0066d
Revises: 7470a48e65d9
Create Date: 2026-01-11 15:54:31.219493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '927c31e0066d'
down_revision: Union[str, None] = '7470a48e65d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_carts', sa.Column('arts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('transactions', sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'items')
    op.drop_column('shopping_carts', 'arts')
    # ### end Alembic commands ###
