"""revise Art table

Revision ID: 9736c7197344
Revises: cf65abaebc55
Create Date: 2026-04-19 13:00:33.037547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9736c7197344'
down_revision: Union[str, None] = 'cf65abaebc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arts', sa.Column('Genres', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('arts', sa.Column('Medium', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('arts', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arts', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('arts', 'Medium')
    op.drop_column('arts', 'Genres')
    # ### end Alembic commands ###
