"""tenth  revise

Revision ID: b90816f5339e
Revises: e3e6c924ad63
Create Date: 2025-10-09 16:21:25.161882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b90816f5339e'
down_revision: Union[str, None] = 'e3e6c924ad63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_carts', 'user_id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_constraint('shopping_carts_user_id_fkey', 'shopping_carts', type_='foreignkey')
    op.alter_column('transactions', 'user_id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['uid'])
    op.alter_column('transactions', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key('shopping_carts_user_id_fkey', 'shopping_carts', 'users', ['user_id'], ['uid'])
    op.alter_column('shopping_carts', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
