"""delete artist table, combine artist with user

Revision ID: bbf7a7261529
Revises: 47a0e3edf42c
Create Date: 2026-01-30 12:00:43.488381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bbf7a7261529'
down_revision: Union[str, None] = '47a0e3edf42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'arts', 'users', ['artist_id'], ['uid'])
    op.add_column('users', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'bio')
    op.drop_constraint(None, 'arts', type_='foreignkey')
    # ### end Alembic commands ###
