"""add imag_url in Art

Revision ID: c08606689987
Revises: df8a918bb7e0
Create Date: 2026-04-19 17:25:25.178810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c08606689987'
down_revision: Union[str, None] = 'df8a918bb7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arts', sa.Column('Genres', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('arts', sa.Column('Medium', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('arts', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('arts', 'genres')
    op.drop_column('arts', 'medium')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arts', sa.Column('medium', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('arts', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('arts', 'image_url')
    op.drop_column('arts', 'Medium')
    op.drop_column('arts', 'Genres')
    # ### end Alembic commands ###
