"""revise shopping cart with user id as primary key and foreign key

Revision ID: e67f9e16e921
Revises: 6efb02fa392c
Create Date: 2026-04-04 11:49:24.327505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e67f9e16e921'
down_revision: Union[str, None] = '6efb02fa392c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_carts', 'uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_carts', sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
